plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '6.0.+'
}

version = '1.0'
group = 'com.javacraft'
archivesBaseName = 'javacraft'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory file('run')
            mods {
                javacraft {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('run')
            mods {
                javacraft {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
